apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates
  description: Root location
spec:
  targets:
    - ./quarkus-application/template.yaml
    - ./quarkus-chatbot/template.yaml
    - ./quarkus-operator/template.yaml
