---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: iocanel
spec:
  displayName: Ioannis Canellos
  email: iocanel@gmail.com
  picture: https://avatars.githubusercontent.com/u/402008
  memberOf: [team]

